CREATE TABLE CHATIK_USER (
    ID NUMBER(10) PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    PASS VARCHAR2(50) NOT NULL
);
CREATE TABLE CHATIK_MESSAGE (
    ID NUMBER(10) PRIMARY KEY,
    TEXT VARCHAR2(200) NOT NULL,
    CHATIK_USER NUMBER(10) NOT NULL,
    CREATE_DATE DATE NOT NULL
);